name: Publish Docker image

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "linux/amd64"
            arch: "amd64"
            toolchain: "x86_64-linux-musl-cross"
            cc: "x86_64-linux-musl-gcc"
          - platform: "linux/arm64"
            arch: "arm64"
            toolchain: "aarch64-linux-musl-cross"
            cc: "aarch64-linux-musl-gcc"
          - platform: "linux/386"
            arch: "386"
            toolchain: "i486-linux-musl-cross"
            cc: "i486-linux-musl-gcc"
          - platform: "linux/s390x"
            arch: "s390x"
            toolchain: "s390x-linux-musl-cross"
            cc: "s390x-linux-musl-gcc"
          - platform: "linux/riscv64"
            arch: "riscv64"
            toolchain: "riscv64-linux-musl-cross"
            cc: "riscv64-linux-musl-gcc"
          - platform: "linux/ppc64le"
            arch: "ppc64le"
            toolchain: "powerpc64le-linux-musl-cross"
            cc: "powerpc64le-linux-musl-gcc"
          - platform: "linux/arm/v6"
            arch: "arm"
            arm: "6"
            toolchain: "armv6-linux-musleabihf-cross"
            cc: "armv6-linux-musleabihf-gcc"
          - platform: "linux/arm/v7"
            arch: "arm"
            arm: "7"
            toolchain: "armv7l-linux-musleabihf-cross"
            cc: "armv7l-linux-musleabihf-gcc"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.GH_REPO }}
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Checkout latest version
        run: |
          version=$(git describe --tags --abbrev=0)
          git checkout "$version"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'web/package.json'
          check-latest: true

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Build frontend
        run: |
          pnpm install
          pnpm build
          cp -a dist/spa/. $GITHUB_WORKSPACE/public/dist/
        working-directory: ./web

      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Install toolchains
        run: |
          curl -L -o "${{matrix.toolchain}}.tgz" "https://musl.cc/${{matrix.toolchain}}.tgz"
          sudo tar xf "${{matrix.toolchain}}.tgz" --strip-components 1 -C /usr/local

      - name: Build
        run: |
          go mod download
          export GOARCH=${{ matrix.arch }}
          if [[ -n "${{ matrix.arm }}" ]]; then
            export GOARM=${{ matrix.arm }}
          fi
          export CC=${{ matrix.cc }}
          bash build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PLATFORM_PAIR }}
          path: kikoeru
          if-no-files-found: error
          retention-days: 1

  push:
    needs: build
    name: Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.GH_REPO }}
          token: ${{ secrets.GH_PAT }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ci.Dockerfile
          platforms: "linux/amd64,linux/arm64,linux/arm/v7,linux/386,linux/arm/v6,linux/s390x,linux/ppc64le,linux/riscv64"
          push: true
          tags: |
            vscodev/kikoeru:latest
            ghcr.io/vscodev/kikoeru:latest
